"""Type stubs for oximedia — Sovereign Media Framework Python bindings."""
from . import cv2 as cv2

# Re-export key classes
class Av1Decoder:
    def send_packet(self, data: bytes, pts: int = 0) -> None: ...
    def receive_frame(self) -> object: ...

class Av1Encoder:
    def __init__(self, config: object) -> None: ...
    def send_frame(self, frame: object) -> None: ...
    def receive_packet(self) -> bytes: ...

class MatroskaDemuxer:
    def __init__(self, path: str) -> None: ...
    def probe(self) -> None: ...
    def streams(self) -> list: ...
    def read_packet(self) -> object: ...
